### ISSUE TITLE
QA_Search Trees_Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/data-structures-iiith#12]
Defect Description:
In the "Search Trees" experiment , the list of experiments link is not present instead the list of experiments link should be displayed on the experiment home page, where the user can easily get back and view the experiments. 

Actual Result :
In the "Search Trees" experiment , the list of experiments link is not  displayed on the experiment home page 

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/data-structures-iiith/blob/master/test-cases/integration_test-cases/Search%20Trees/Search%20Trees_13_Back%20to%20experiment_smk.org

Attachment:
![bte](https://cloud.githubusercontent.com/assets/14869397/14777857/57c1343c-0aed-11e6-9450-0e8055b057c0.png)

**Comment by khushpreet-kaur** [comment]
This issue is resolved now, `List of experiments` link is present on this page.

**Comment by BSravanthi** [comment]
The **List of Experiments** link is not included yet.

**Comment by khushpreet-kaur** [comment]
Done.

**Comment by BSravanthi** [comment]
Closed #12
