### ISSUE TITLE
Number-Systems_Theory

### ISSUE THREAD

**Issue by adityaddy** [virtual-labs/data-structures-iiith#235]
**Description** - No space between SystemUsed
**Steps to reproduce the issue** - Open the Theory part of Number-System experiment
**Expected Result** - System Used
**Actual Result** - SystemUsed
![issues1](https://user-images.githubusercontent.com/42521005/54476122-84295c80-481f-11e9-8a16-3dc89b7a6a45.png)

**Comment by hbrk** [comment]
Fixed Issue
**Commit Id.**:509fe4a

**Comment by adityaddy** [comment]
Fixed 
commit id: #4929349
