### ISSUE TITLE
QA_Sorting using Arrays_Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/data-structures-iiith#26]
Defect Description:
In the "Sorting using Arrays" experiment , the list of experiments link is not present instead the list of experiments link should be displayed on the experiment home page, where the user can easily get back and view the experiments.     

Actual Result :
In the "Sorting using Arrays" experiment , the list of experiments link is not  displayed on the experiment home page  

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/data-structures-iiith/blob/master/test-cases/integration_test-cases/Sorting%20using%20Arrays/Sorting%20using%20Arrays_16_Back%20to%20experiment_smk.org

Attachment:
![ds9](https://cloud.githubusercontent.com/assets/14869397/14776275/1fcfb63e-0ae3-11e6-941b-5002affd129a.png)

**Comment by khushpreet-kaur** [comment]
This issue is resolved now, `List of experiments` link is present on this page.

**Comment by BSravanthi** [comment]
The List of Experiments link is not included yet.

**Comment by khushpreet-kaur** [comment]
This issue has been resolved.

**Comment by BSravanthi** [comment]
Closed #26
