### ISSUE TITLE
QA_Number Systems_Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/data-structures-iiith#33]
Defect Description:
In the "Number Systems" experiment , the list of experiments link is not present instead the list of experiments link should be displayed on the experiment home page, where the user can easily get back and view the experiments.

Actual Result :
In the "Number Systems" experiment , the list of experiments link is not  displayed on the experiment home page 

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/data-structures-iiith/blob/master/test-cases/integration_test-cases/Number%20Systems/Number%20Systems_32_Back%20to%20experiment_smk.org

Attachment:
![ds1](https://cloud.githubusercontent.com/assets/14869397/14774197/1296ab38-0ad1-11e6-87b1-0b9916892008.png)

**Comment by khushpreet-kaur** [comment]
This issue is resolved now, `List of experiments` link is present on this page.

**Comment by BSravanthi** [comment]
The List of Experiments links is not updated on the above mentioned page.

**Comment by BSravanthi** [comment]
Closed #33
