### ISSUE TITLE
Update the Disciplines and Domains field with the concerned information.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/data-structures-iiith#36]
As the Data Structures lab belongs to Computer Science and Engineering discipline/domain, need the field is updated with the appropriate discipline/domain.

![ds-qa-i1](https://cloud.githubusercontent.com/assets/13479177/16976774/ca9524d0-4e6a-11e6-8b1e-f74eb87afb4d.png)

**Comment by khushpreet-kaur** [comment]
Issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #36
