### ISSUE TITLE
Numbering in the Itroduction page of Data Structures lab.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/data-structures-iiith#39]
The Numbering if the points is improper in the Introduction page of Number Systems experiment of Data Structures lab.  Even the alignment needs to be set right.

![ds-qa-i2](https://cloud.githubusercontent.com/assets/13479177/16981296/69aa391c-4e83-11e6-882c-8d76603f0f61.png)

**Comment by khushpreet-kaur** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #39
