### ISSUE TITLE
Improper alignment in few pages of this lab's Experiment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/data-structures-iiith#42]
In the Theory page of Expression Evaluation experiment(exp2) of this lab has improper alignment of data is present.
In the Quizzes page of  Polynomials via Linked Lists (Exp4) of Data Structures lab, improper alignment is present.

**Comment by khushpreet-kaur** [comment]
Issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #42
