### ISSUE TITLE
Numbering correction in the theory page of Sorting using arrays of Data Structures lab.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/data-structures-iiith#43]
The below screen shot belongs to the Theory page of Sorting Using Arrays Experiment of Data Structures lab, In the theory part of Quick sort, 4th point is missing. Need to include 4th point or may need to correct the numbering. 

![ds-qa-i3](https://cloud.githubusercontent.com/assets/13479177/16983655/4fa1f5bc-4e8f-11e6-8a0b-3140201f4f7a.png)

**Comment by khushpreet-kaur** [comment]
This issue has been resolved now.

**Comment by BSravanthi** [comment]
Need to adjust the alignment and need to remove either bullets or numbering.

**Comment by khushpreet-kaur** [comment]
Done.

**Comment by BSravanthi** [comment]
Closed #43
