### ISSUE TITLE
URL differs from the experiment name in Expression Trees Experiment.

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/data-structures-iiith#44]
## In all the 5 pages of  **Expression Trees** experiment(exp5), the URL is given as exp6.

 
![da-qa-i4](https://cloud.githubusercontent.com/assets/13479177/17014504/53c893d0-4f3e-11e6-82fd-15905ed471a4.png)

**Comment by khushpreet-kaur** [comment]
Issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #44
