### ISSUE TITLE
URL differs from the experiment name in Search Trees Experiment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/data-structures-iiith#45]
# In all the 6 pages of Search Trees experiment(exp6, the URL is given as exp 6

![ds-qa-i4](https://cloud.githubusercontent.com/assets/13479177/17014567/955bc682-4f3e-11e6-84fe-14fb6f9708dd.png)

**Comment by khushpreet-kaur** [comment]
Issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #45
