### ISSUE TITLE
Minor corrections in Quizzes page of Data Structures lab

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/data-structures-iiith#46]
In the  Quizzes page of **Expression Evaluation using Stacks** experiment in the Data Structures lab, can give either numbering or bullets to questions
In the Quizzes page of **Sorting using Arrays** experiment in the Data Structures lab, both bullets and numbering has given. Any one can be removed in order to  maintain the look and feel of the page.
In the Quizzes page of **Polynomials via Linked Lists** experiment in the Data Structures lab,  both bullets and numbering has given. Any one can be removed in order to maintain the look and feel of the page.
In the Quizzes page of **Expression Trees**experiment in the Data Structures lab, the Bullet needs to be removed from the "Easy Questions" heading.
In the Simulation page of **Search Trees** and **Graph Traversals** Experiments in the Data Structures lab, the heading of "Simulation" is given where as in other Experiments such heading is not present. 
In the Quizzes page of **Search Trees** experiment in the Data Structures lab, Need to give Numbering for the questions in order to maintain the look and feel of the page.

**Comment by khushpreet-kaur** [comment]
All the above issues are resolved.

**Comment by BSravanthi** [comment]
Closed #46
