### ISSUE TITLE
Change of name of the lab in the Graph Traversals Experiment of Data Structures lab

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/data-structures-iiith#47]
In the Graph Traversals Experiment of Data Structures lab, near "Computer Science & Engineering and List Of Experiments" links the name of the lab is given as **Problem Solving Lab** instead of **Data Structures lab** in all the five pages. 

![ds-qa-i5](https://cloud.githubusercontent.com/assets/13479177/17022428/54037940-4f67-11e6-8d04-68f1934f8243.png)

**Comment by khushpreet-kaur** [comment]
Issue is resolved now. Update the right lab name.

**Comment by BSravanthi** [comment]
Closed #47
