### ISSUE TITLE
Change of name of the lab in the Minimum Spanning Trees Experiment of Data Structures lab

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/data-structures-iiith#48]
In the Minimum Spanning Trees Experiment of Data Structures lab, near "Computer Science & Engineering and List Of Experiments" links the name of the lab is given as Problem Solving Lab instead of Data Structures lab in all the five pages. 

![ds-qa-i6](https://cloud.githubusercontent.com/assets/13479177/17022560/1e74a118-4f68-11e6-8bc9-3d811db10c26.png)

**Comment by khushpreet-kaur** [comment]
This issue has been resolved.

**Comment by BSravanthi** [comment]
Closed #48
