### ISSUE TITLE
QA_DataStructures_Junkdata

### ISSUE THREAD

**Issue by sadhanareddy** [virtual-labs/data-structures-iiith#53]
Defect Description :
When we double click on the home page content section of this lab some hidden content is getting displayed. Instead nothing should be displayed on the page.

Actual Result :
When we double click on the home of this lab some hidden content is getting displayed.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
Find the screenshots:
![image1](https://cloud.githubusercontent.com/assets/11345237/19918893/01258850-a0f5-11e6-85ea-b3352eb4cf83.png)

![image2](https://cloud.githubusercontent.com/assets/11345237/19918897/0a795896-a0f5-11e6-9e5e-aab3ca8c4454.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now. Hence closing the issue.
