### ISSUE TITLE
QA_DataStructures_brokenlink in edx

### ISSUE THREAD

**Issue by sadhanareddy** [virtual-labs/data-structures-iiith#54]
Defect Description :
In this lab "view unit in studio" link is not working. Whereas it should redirect to the appropriate page.

Actual Result :
In this lab "view unit in studio link"  is not working.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by sravanthimodepu** [comment]
Not yet resolved the issue.

Attachment
Follow the below image:
![ds-course-view-unit](https://cloud.githubusercontent.com/assets/11156924/25982793/1ce19fae-36fd-11e7-8a3a-c19c2a5025fa.png)
