### ISSUE TITLE
QA_Sorting using Arrays_Simulation_Name differs. 

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/data-structures-iiith#56]
Defect Description:
In the Simulation page of "Sorting Using Arrays" of this lab, the title of the first experiment is given as **Expression Evaluation using Stacks** instead of **Quick Sort**. 

Actual Result :
In the Simulation page of "Sorting Using Arrays" of this lab, the title of the first experiment is given as **Expression Evaluation using Stacks** instead of **Quick Sort**. 

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachment:
![qa_ds_i1](https://cloud.githubusercontent.com/assets/13479177/25122425/791692fc-2442-11e7-920f-1ead5b04ce1e.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed.
